DNA_reverse_complement = {'A': 'T', 'T': 'A', 'G': 'C', 'C': 'G'}


def reverse_complement(seq):
    return ''.join([DNA_reverse_complement[nuc] for nuc in seq])[::-1]


reverse_complement_string = reverse_complement('CCGGCGGACGATGAAAGGACAACTATGTGCGCCCACCGGGAACTTCCACGACCATAAAATCGTAGGGCAAACAAGAGCCAACCATATGTCATCTTCACGATGCGGACGACGACACAAACCGCCGTTTAAACTATAGCGCGCCCTTGAACGAAGGAACTCTTGTCCAACGGAGCCCTCATGAATCAGAGAGGGAGGTAGACTGCGACCTCTATAAAAAGTGTACGTATGTTTCCTCAGTACACAGACGCTTAGAACTTGATCCGTGATAAATTACAATACCAAACAAGGGCCTCTTTCGTCGACACAGCTGGCATCCCCAGTACTTTGTGTATGAGTTGCTAGGGGAGCTGCAGATTGATTGGCTTCGCCCCCATGCCCAGTTGTACCAGATTGAATGGTCTACTATCCGCGGAAACGATAGGACCTATACTGACAAAGCCCGGAAATACGAAGGATTAGTTATTTGAAGTGGATATGTGCACTCATGTGGGGCGTCCTAGAAGGAGTGCTGACAGGAGCGGTGTCAAGATCATGTTAAAGCAAGGTACGAAGGGACGGGAGTCACGGGCCGACTATACGCAGAAAACATGTTTCTCTCGGTCGCTGGCCGGGACGTGCATCAGGGACCTCGAAAGCAACCTGCACCACGGTAAATCAGATACTTCTTAAGCTCGTGCACGCTATATAGATCGGACATAGCAGGGGAAGGTTCGCAGACCTTGATCTTTCCTACTGACGGCCAATCGACGTTCTCATCCTGCAGTTGTACGTGCGAGTTTCTATTCGTAGCTGGAACGTGGTCGATTCCACACCCACACCAGAGAGTGAAATGAACGTGGATCACATGGAGCCTGGAACCTTCACAGTGTT')

print(reverse_complement_string)

#
# sample_output = 'ACCGGGTTTT'
#
# if sample_output == reverse_complement_string:
#     print('MATCH \n')
#     print('reverse_complement_string: {}'.format(reverse_complement_string))
#     print('sample_output: {}'.format(sample_output))
# else:
#     print('NO MATCH')
